FROM oven/bun:alpine AS builder
WORKDIR /app

COPY package.json bun.lockb* ./
RUN bun install --ci

COPY . .
RUN bun run build

FROM oven/bun:alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

CMD ["bun", "run", "start"]
