services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: icn_todos
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: dev
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: bun run dev
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: bun run dev -- -H 0.0.0.0 -p 3000
    depends_on:
      - backend

volumes:
  database-data:
